# Generated by Django 6.1 on 2026-08-09 23:00

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("caja", "0001_initial"),
        ("clientes", "0001_initial"),
        ("core", "0001_initial"),
        ("productos", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Presupuesto",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("numero", models.CharField(blank=True, max_length=40)),
                (
                    "total",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                ("estado", models.CharField(default="pendiente", max_length=40)),
                ("validez", models.DateField(blank=True, null=True)),
                (
                    "cliente",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="clientes.cliente",
                    ),
                ),
                (
                    "comercio",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.comercio"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="PresupuestoItem",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "cantidad",
                    models.DecimalField(decimal_places=3, default=1, max_digits=14),
                ),
                (
                    "precio_unitario",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                (
                    "subtotal",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                (
                    "presupuesto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="ventas.presupuesto",
                    ),
                ),
                (
                    "producto",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="productos.producto",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Venta",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("numero_ticket", models.BigIntegerField(blank=True, null=True)),
                (
                    "total",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                (
                    "descuento",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                (
                    "recargo_monto",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                (
                    "comision_monto",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                ("metodo_pago", models.CharField(blank=True, max_length=40)),
                (
                    "monto_efectivo",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                (
                    "monto_tarjeta",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                (
                    "monto_transferencia",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                (
                    "efectivo_recibido",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=14, null=True
                    ),
                ),
                (
                    "vuelto",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=14, null=True
                    ),
                ),
                ("origen", models.CharField(default="pos", max_length=40)),
                ("anulada", models.BooleanField(default=False)),
                ("motivo_anulacion", models.CharField(blank=True, max_length=300)),
                ("fecha_anulacion", models.DateTimeField(blank=True, null=True)),
                ("facturado", models.BooleanField(default=False)),
                ("excluir_fiscal", models.BooleanField(default=False)),
                ("cae", models.CharField(blank=True, max_length=40)),
                ("cae_vencimiento", models.DateField(blank=True, null=True)),
                ("tipo_factura", models.CharField(blank=True, max_length=5)),
                ("numero_factura", models.CharField(blank=True, max_length=40)),
                ("punto_venta_factura", models.CharField(blank=True, max_length=20)),
                ("fecha_facturacion", models.DateTimeField(blank=True, null=True)),
                ("comprador_fiscal", models.CharField(blank=True, max_length=200)),
                ("comprador_datos", models.JSONField(blank=True, null=True)),
                (
                    "caja_sesion",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="caja.cajasesion",
                    ),
                ),
                (
                    "cliente",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="clientes.cliente",
                    ),
                ),
                (
                    "comercio",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.comercio"
                    ),
                ),
                (
                    "cuenta_pago",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="caja.cuentapago",
                    ),
                ),
                (
                    "vendedor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="core.perfil",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="VentaItem",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "cantidad",
                    models.DecimalField(decimal_places=3, default=1, max_digits=14),
                ),
                (
                    "peso_kg",
                    models.DecimalField(
                        blank=True, decimal_places=3, max_digits=14, null=True
                    ),
                ),
                (
                    "precio_unitario",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                (
                    "costo_unitario",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                (
                    "subtotal",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                (
                    "combo",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="productos.combo",
                    ),
                ),
                (
                    "producto",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="productos.producto",
                    ),
                ),
                (
                    "venta",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="ventas.venta",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddIndex(
            model_name="venta",
            index=models.Index(
                fields=["comercio", "-created_at"],
                name="ventas_vent_comerci_2e7082_idx",
            ),
        ),
    ]
