# Generated by Django 6.1 on 2026-08-10 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("caja", "0001_initial"),
        ("clientes", "0001_initial"),
        ("core", "0001_initial"),
        ("ventas", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="venta",
            name="sync_uuid",
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddConstraint(
            model_name="venta",
            constraint=models.UniqueConstraint(
                condition=models.Q(("sync_uuid__isnull", False)),
                fields=("comercio", "sync_uuid"),
                name="unique_venta_sync_uuid_por_comercio",
            ),
        ),
    ]
