# Generated by Django 6.1 on 2026-08-11 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0002_venta_sync_uuid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='monto_cuenta_corriente',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
    ]
