# Generated by Django 6.1 on 2026-08-21 00:50

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("caja", "0003_cajamovimiento_cuenta_and_more"),
        ("ventas", "0003_venta_monto_cuenta_corriente"),
    ]

    operations = [
        migrations.CreateModel(
            name="VentaPago",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("monto", models.DecimalField(decimal_places=2, max_digits=14)),
                (
                    "cuenta_pago",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="caja.cuentapago",
                    ),
                ),
                (
                    "venta",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pagos",
                        to="ventas.venta",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
