# Generated by Django 6.1 on 2026-08-21 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clientes", "0003_clientemovimiento_medio_pago"),
        ("core", "0003_comercio_asistente_api_key_cifrada_and_more"),
        ("ventas", "0004_ventapago"),
    ]

    operations = [
        migrations.AddField(
            model_name="presupuesto",
            name="cliente_nombre",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="presupuesto",
            name="descuento",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name="presupuesto",
            name="notas",
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name="presupuesto",
            name="subtotal",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name="presupuestoitem",
            name="es_bolsa",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="presupuesto",
            name="estado",
            field=models.CharField(
                choices=[
                    ("pendiente", "pendiente"),
                    ("aprobado", "aprobado"),
                    ("rechazado", "rechazado"),
                    ("vencido", "vencido"),
                ],
                default="pendiente",
                max_length=20,
            ),
        ),
        migrations.AddIndex(
            model_name="presupuesto",
            index=models.Index(
                fields=["comercio", "-created_at"],
                name="ventas_pres_comerci_df3b2b_idx",
            ),
        ),
    ]
