# Generated by Django 6.1 on 2026-08-22 23:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("caja", "0003_cajamovimiento_cuenta_and_more"),
        ("ventas", "0005_presupuesto_cliente_nombre_presupuesto_descuento_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="venta",
            name="vuelto_cuenta_pago",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="caja.cuentapago",
            ),
        ),
    ]
