# Generated by Django 6.1 on 2026-08-27 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0006_venta_vuelto_cuenta_pago'),
    ]

    operations = [
        migrations.AddField(
            model_name='ventaitem',
            name='descuento_pct',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
