# Generated by Django 6.1 on 2026-08-28 22:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0007_ventaitem_descuento_pct'),
    ]

    operations = [
        migrations.AddField(
            model_name='presupuesto',
            name='venta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ventas.venta'),
        ),
        migrations.AlterField(
            model_name='presupuesto',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'pendiente'), ('aprobado', 'aprobado'), ('rechazado', 'rechazado'), ('vencido', 'vencido'), ('cobrado', 'cobrado')], default='pendiente', max_length=20),
        ),
    ]
