# Generated by Django 6.1 on 2026-08-29 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caja', '0004_cajaconteo'),
        ('clientes', '0003_clientemovimiento_medio_pago'),
        ('core', '0004_comercio_permitir_venta_sin_stock'),
        ('ventas', '0008_presupuesto_venta_alter_presupuesto_estado'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='venta',
            index=models.Index(fields=['comercio', 'numero_ticket'], name='ventas_vent_comerci_fa5127_idx'),
        ),
    ]
