# Generated by Django 6.1 on 2026-08-09 23:00

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AlertaLeida",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("user_id", models.UUIDField(blank=True, null=True)),
                ("alerta_key", models.CharField(blank=True, max_length=120)),
                (
                    "comercio",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.comercio"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("user_id", models.UUIDField(blank=True, null=True)),
                ("accion", models.CharField(blank=True, max_length=60)),
                ("entidad", models.CharField(blank=True, max_length=60)),
                ("entidad_id", models.UUIDField(blank=True, null=True)),
                ("datos", models.JSONField(blank=True, null=True)),
                (
                    "comercio",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.comercio"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ErrorLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("user_id", models.UUIDField(blank=True, null=True)),
                ("user_nombre", models.CharField(blank=True, max_length=200)),
                ("tipo", models.CharField(blank=True, max_length=60)),
                ("mensaje", models.TextField(blank=True)),
                ("stack", models.TextField(blank=True)),
                ("url", models.CharField(blank=True, max_length=500)),
                ("linea", models.IntegerField(blank=True, null=True)),
                ("columna", models.IntegerField(blank=True, null=True)),
                ("user_agent", models.CharField(blank=True, max_length=400)),
                ("modulo", models.CharField(blank=True, max_length=60)),
                (
                    "comercio",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.comercio"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="UiEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("modulo", models.CharField(blank=True, max_length=60)),
                ("elemento", models.CharField(blank=True, max_length=120)),
                ("x", models.IntegerField(blank=True, null=True)),
                ("y", models.IntegerField(blank=True, null=True)),
                (
                    "comercio",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.comercio"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="UiHeatmap",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("modulo", models.CharField(blank=True, max_length=60)),
                ("fecha", models.DateField(blank=True, null=True)),
                ("viewport_w", models.IntegerField(blank=True, null=True)),
                ("viewport_h", models.IntegerField(blank=True, null=True)),
                ("grid", models.JSONField(blank=True, null=True)),
                ("sesion_count", models.IntegerField(default=0)),
                (
                    "comercio",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.comercio"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
