# Generated by Django 6.1 on 2026-08-21 01:48

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AccionPendiente",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("alta_producto", "alta de producto"),
                            ("venta", "venta"),
                        ],
                        max_length=30,
                    ),
                ),
                ("resumen", models.TextField()),
                ("datos", models.JSONField()),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("pendiente", "pendiente"),
                            ("confirmada", "confirmada"),
                            ("cancelada", "cancelada"),
                        ],
                        default="pendiente",
                        max_length=20,
                    ),
                ),
                ("resultado_id", models.UUIDField(blank=True, null=True)),
                (
                    "comercio",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.comercio"
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["comercio", "estado"],
                        name="asistente_a_comerci_f5f91d_idx",
                    )
                ],
            },
        ),
    ]
