# Generated by Django 6.1 on 2026-08-21 02:03

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("asistente", "0001_initial"),
        ("core", "0002_comercio_asistente_consultas_diarias"),
    ]

    operations = [
        migrations.CreateModel(
            name="UsoAsistente",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("fecha", models.DateField()),
                ("consultas", models.IntegerField(default=0)),
                ("tokens_entrada", models.BigIntegerField(default=0)),
                ("tokens_cacheados", models.BigIntegerField(default=0)),
                ("tokens_salida", models.BigIntegerField(default=0)),
                (
                    "comercio",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.comercio"
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["comercio", "-fecha"],
                        name="asistente_u_comerci_6fcf76_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("comercio", "fecha"), name="uso_asistente_unico_por_dia"
                    )
                ],
            },
        ),
    ]
