# Generated by Django 6.1 on 2026-08-19 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clientes", "0002_clientemovimiento"),
    ]

    operations = [
        migrations.AddField(
            model_name="clientemovimiento",
            name="medio_pago",
            field=models.CharField(
                blank=True,
                choices=[
                    ("efectivo", "Efectivo"),
                    ("transferencia", "Transferencia"),
                    ("tarjeta", "Tarjeta"),
                ],
                max_length=20,
            ),
        ),
    ]
