# Generated by Django 6.1 on 2026-09-02 14:36

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0003_clientemovimiento_medio_pago'),
        ('core', '0006_comercio_color_acento'),
    ]

    operations = [
        migrations.CreateModel(
            name='MovimientoAuditoria',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cliente_nombre', models.CharField(max_length=200)),
                ('accion', models.CharField(choices=[('editado', 'editado'), ('eliminado', 'eliminado')], max_length=20)),
                ('motivo', models.CharField(max_length=300)),
                ('movimiento_id', models.UUIDField()),
                ('tipo', models.CharField(max_length=30)),
                ('monto_anterior', models.DecimalField(decimal_places=2, max_digits=14)),
                ('referencia_anterior', models.CharField(blank=True, max_length=120)),
                ('medio_pago_anterior', models.CharField(blank=True, max_length=20)),
                ('monto_nuevo', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('referencia_nueva', models.CharField(blank=True, max_length=120)),
                ('medio_pago_nuevo', models.CharField(blank=True, max_length=20)),
                ('saldo_anterior', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('saldo_nuevo', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auditorias', to='clientes.cliente')),
                ('comercio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.comercio')),
                ('hecho_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.perfil')),
            ],
            options={
                'indexes': [models.Index(fields=['comercio', '-created_at'], name='clientes_mo_comerci_5894c6_idx')],
            },
        ),
    ]
