# Generated by Django 6.1 on 2026-09-02 15:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caja', '0004_cajaconteo'),
        ('clientes', '0004_movimientoauditoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientemovimiento',
            name='caja_sesion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='caja.cajasesion'),
        ),
        migrations.AddField(
            model_name='clientemovimiento',
            name='cuenta_pago',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='caja.cuentapago'),
        ),
    ]
