# Generated by Django 6.1 on 2026-08-20 21:22

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("clientes", "0003_clientemovimiento_medio_pago"),
        ("core", "0001_initial"),
        ("productos", "0004_producto_stock_en_bolsas"),
    ]

    operations = [
        migrations.CreateModel(
            name="Reparto",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("cliente_nombre", models.CharField(max_length=200)),
                ("telefono", models.CharField(blank=True, max_length=50)),
                ("destino", models.CharField(max_length=300)),
                ("fecha", models.DateField()),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("pendiente", "pendiente"),
                            ("en_camino", "en camino"),
                            ("entregado", "entregado"),
                            ("cancelado", "cancelado"),
                        ],
                        default="pendiente",
                        max_length=20,
                    ),
                ),
                ("notas", models.CharField(blank=True, max_length=300)),
                (
                    "subtotal",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                (
                    "costo_envio",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                (
                    "descuento",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                (
                    "total",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                (
                    "cliente",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="clientes.cliente",
                    ),
                ),
                (
                    "comercio",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.comercio"
                    ),
                ),
                (
                    "repartidor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="core.perfil",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RepartoItem",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "cantidad",
                    models.DecimalField(decimal_places=3, default=1, max_digits=14),
                ),
                ("es_bolsa", models.BooleanField(default=False)),
                (
                    "precio_unitario",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                (
                    "subtotal",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                (
                    "producto",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="productos.producto",
                    ),
                ),
                (
                    "reparto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="repartos.reparto",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddIndex(
            model_name="reparto",
            index=models.Index(
                fields=["comercio", "-fecha"], name="repartos_re_comerci_becd64_idx"
            ),
        ),
    ]
