# Generated by Django 6.1 on 2026-09-01 13:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repartos', '0001_initial'),
        ('ventas', '0009_venta_ventas_vent_comerci_fa5127_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='reparto',
            name='venta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ventas.venta'),
        ),
    ]
