# Generated by Django 6.1 on 2026-09-01 17:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caja', '0004_cajaconteo'),
        ('repartos', '0002_reparto_venta'),
    ]

    operations = [
        migrations.AddField(
            model_name='reparto',
            name='a_cuenta_corriente',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='reparto',
            name='cuenta_pago',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='caja.cuentapago'),
        ),
    ]
