# Generated by Django 6.1 on 2026-08-09 23:00

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0001_initial"),
        ("ventas", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ComercioFiscalConfig",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("cuit", models.CharField(blank=True, max_length=20)),
                ("razon_social", models.CharField(blank=True, max_length=200)),
                ("punto_venta", models.CharField(blank=True, max_length=20)),
                ("condicion_iva", models.CharField(blank=True, max_length=60)),
                ("es_principal", models.BooleanField(default=False)),
                ("cert_ref", models.CharField(blank=True, max_length=200)),
                ("activo", models.BooleanField(default=True)),
                (
                    "comercio",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.comercio"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="FiscalBatch",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("status", models.CharField(default="pendiente", max_length=30)),
                ("cantidad", models.IntegerField(default=0)),
                (
                    "comercio",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.comercio"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="FiscalQueue",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("status", models.CharField(default="pendiente", max_length=30)),
                ("cae", models.CharField(blank=True, max_length=40)),
                ("cae_vencimiento", models.DateField(blank=True, null=True)),
                ("punto_venta", models.CharField(blank=True, max_length=20)),
                ("numero_factura", models.CharField(blank=True, max_length=40)),
                ("tipo_comprobante", models.CharField(blank=True, max_length=20)),
                ("error_msg", models.TextField(blank=True)),
                (
                    "batch",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="fiscal.fiscalbatch",
                    ),
                ),
                (
                    "comercio",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.comercio"
                    ),
                ),
                (
                    "venta",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ventas.venta",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
