# Generated by Django 6.1 on 2026-08-14 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fiscal", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="comerciofiscalconfig",
            name="homologacion",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="comerciofiscalconfig",
            name="condicion_iva",
            field=models.CharField(
                blank=True,
                choices=[
                    ("monotributo", "Monotributo"),
                    ("responsable_inscripto", "Responsable Inscripto"),
                    ("exento", "Exento"),
                ],
                max_length=60,
            ),
        ),
    ]
