# Generated by Django 6.1 on 2026-08-23 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fiscal", "0002_comerciofiscalconfig_homologacion_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="comerciofiscalconfig",
            name="facturar_automatico",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="comerciofiscalconfig",
            name="facturar_medios",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="comerciofiscalconfig",
            name="facturar_monto_minimo",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
    ]
