# Generated by Django 6.1 on 2026-08-09 23:00

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0001_initial"),
        ("productos", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ConsumoInterno",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("persona", models.CharField(blank=True, max_length=200)),
                ("tipo_precio", models.CharField(default="costo", max_length=20)),
                (
                    "total_costo",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                ("fecha", models.DateTimeField(auto_now_add=True)),
                (
                    "comercio",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.comercio"
                    ),
                ),
                (
                    "persona_ref",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="core.perfil",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ConsumoInternoItem",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("nombre_producto", models.CharField(blank=True, max_length=200)),
                (
                    "cantidad",
                    models.DecimalField(decimal_places=3, default=1, max_digits=14),
                ),
                (
                    "peso_kg",
                    models.DecimalField(
                        blank=True, decimal_places=3, max_digits=14, null=True
                    ),
                ),
                ("unidad_medida", models.CharField(blank=True, max_length=20)),
                (
                    "precio_costo",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=14, null=True
                    ),
                ),
                (
                    "precio_venta",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=14, null=True
                    ),
                ),
                (
                    "subtotal",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=14, null=True
                    ),
                ),
                (
                    "consumo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="finanzas.consumointerno",
                    ),
                ),
                (
                    "producto",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="productos.producto",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Gasto",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("categoria", models.CharField(blank=True, max_length=120)),
                ("descripcion", models.CharField(blank=True, max_length=300)),
                (
                    "monto",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                ("fecha", models.DateField()),
                (
                    "comercio",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.comercio"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
