# Generated by Django 6.1 on 2026-08-10 20:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caja', '0002_cajasesion_unique_caja_sesion_abierta_por_comercio'),
        ('finanzas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gasto',
            name='caja_sesion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='caja.cajasesion'),
        ),
    ]
