# Generated by Django 6.1 on 2026-08-10 21:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caja', '0003_cajamovimiento_cuenta_and_more'),
        ('finanzas', '0002_gasto_caja_sesion'),
    ]

    operations = [
        migrations.AddField(
            model_name='gasto',
            name='cuenta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='caja.cuentapago'),
        ),
    ]
