# Generated by Django 6.1 on 2026-08-22 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finanzas", "0003_gasto_cuenta"),
    ]

    operations = [
        migrations.AddField(
            model_name="gasto",
            name="tipo",
            field=models.CharField(
                choices=[("fijo", "Fijo"), ("variable", "Variable")],
                default="variable",
                max_length=20,
            ),
        ),
    ]
