# Generated by Django 6.1 on 2026-08-12 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("inventario", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="BaldeHeladeria",
        ),
    ]
