# Generated by Django 6.1 on 2026-08-12 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("productos", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="producto",
            name="plu_balanza",
        ),
    ]
