# Generated by Django 6.1 on 2026-08-12 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("productos", "0002_remove_producto_plu_balanza"),
    ]

    operations = [
        migrations.AddField(
            model_name="producto",
            name="bolsa_kg",
            field=models.DecimalField(
                blank=True, decimal_places=3, max_digits=14, null=True
            ),
        ),
        migrations.AddField(
            model_name="producto",
            name="precio_bolsa",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=14, null=True
            ),
        ),
    ]
