# Generated by Django 6.1 on 2026-08-20 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("productos", "0003_producto_bolsa_kg_producto_precio_bolsa"),
    ]

    operations = [
        migrations.AddField(
            model_name="producto",
            name="stock_en_bolsas",
            field=models.BooleanField(default=False),
        ),
    ]
