# Generated by Django 6.1 on 2026-08-24 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("productos", "0004_producto_stock_en_bolsas"),
    ]

    operations = [
        migrations.AlterField(
            model_name="producto",
            name="unidad_medida",
            field=models.CharField(
                choices=[
                    ("unidad", "unidad"),
                    ("kg", "kg"),
                    ("g", "g"),
                    ("lt", "lt"),
                    ("m", "m"),
                ],
                default="unidad",
                max_length=20,
            ),
        ),
    ]
