# Generated by Django 6.1 on 2026-08-24 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("productos", "0005_alter_producto_unidad_medida"),
    ]

    operations = [
        migrations.AlterField(
            model_name="producto",
            name="precio_costo",
            field=models.DecimalField(decimal_places=4, default=0, max_digits=14),
        ),
    ]
