# Generated by Django 6.1 on 2026-08-09 23:00

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CajaSesion",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "estado",
                    models.CharField(
                        choices=[("abierta", "abierta"), ("cerrada", "cerrada")],
                        default="abierta",
                        max_length=20,
                    ),
                ),
                (
                    "monto_apertura",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                (
                    "monto_cierre",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=14, null=True
                    ),
                ),
                (
                    "monto_esperado",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=14, null=True
                    ),
                ),
                (
                    "diferencia",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=14, null=True
                    ),
                ),
                ("fecha_apertura", models.DateTimeField(auto_now_add=True)),
                ("fecha_cierre", models.DateTimeField(blank=True, null=True)),
                (
                    "cajero",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="core.perfil",
                    ),
                ),
                (
                    "comercio",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.comercio"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="CajaMovimiento",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("tipo", models.CharField(max_length=20)),
                ("concepto", models.CharField(blank=True, max_length=200)),
                ("monto", models.DecimalField(decimal_places=2, max_digits=14)),
                (
                    "comercio",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.comercio"
                    ),
                ),
                (
                    "sesion",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="caja.cajasesion",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="CuentaPago",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("nombre", models.CharField(max_length=120)),
                ("tipo", models.CharField(blank=True, max_length=40)),
                (
                    "comision_pct",
                    models.DecimalField(decimal_places=2, default=0, max_digits=6),
                ),
                ("activo", models.BooleanField(default=True)),
                (
                    "comercio",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.comercio"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
