# Generated by Django 6.1 on 2026-08-10 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caja', '0001_initial'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='cajasesion',
            constraint=models.UniqueConstraint(condition=models.Q(('estado', 'abierta')), fields=('comercio',), name='unique_caja_sesion_abierta_por_comercio'),
        ),
    ]
