# Generated by Django 6.1 on 2026-08-10 21:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caja', '0002_cajasesion_unique_caja_sesion_abierta_por_comercio'),
    ]

    operations = [
        migrations.AddField(
            model_name='cajamovimiento',
            name='cuenta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='caja.cuentapago'),
        ),
        migrations.AddField(
            model_name='cajamovimiento',
            name='transferencia_id',
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
