# Generated by Django 6.1 on 2026-08-24 15:50

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("caja", "0003_cajamovimiento_cuenta_and_more"),
        ("core", "0004_comercio_permitir_venta_sin_stock"),
    ]

    operations = [
        migrations.CreateModel(
            name="CajaConteo",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "esperado",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                (
                    "contado",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                (
                    "comercio",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.comercio"
                    ),
                ),
                (
                    "cuenta",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="caja.cuentapago",
                    ),
                ),
                (
                    "sesion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="conteos",
                        to="caja.cajasesion",
                    ),
                ),
            ],
            options={
                "unique_together": {("sesion", "cuenta")},
            },
        ),
    ]
