# Generated by Django 6.1 on 2026-08-09 23:00

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0001_initial"),
        ("productos", "0001_initial"),
        ("proveedores", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Compra",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("numero_factura", models.CharField(blank=True, max_length=40)),
                ("fecha", models.DateField()),
                (
                    "total",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                ("pagado", models.BooleanField(default=False)),
                (
                    "comercio",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.comercio"
                    ),
                ),
                (
                    "proveedor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="proveedores.proveedor",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="CompraItem",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "cantidad",
                    models.DecimalField(decimal_places=3, default=1, max_digits=14),
                ),
                (
                    "costo_unitario",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                (
                    "subtotal",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                (
                    "compra",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="compras.compra",
                    ),
                ),
                (
                    "producto",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="productos.producto",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
