# Generated by Django 6.1 on 2026-08-23 01:40

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("caja", "0003_cajamovimiento_cuenta_and_more"),
        ("compras", "0002_compra_caja_sesion"),
        ("core", "0003_comercio_asistente_api_key_cifrada_and_more"),
        ("proveedores", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CompraPago",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("fecha", models.DateField()),
                ("monto", models.DecimalField(decimal_places=2, max_digits=14)),
                ("notas", models.CharField(blank=True, max_length=300)),
            ],
        ),
        migrations.AddField(
            model_name="compra",
            name="fecha_vencimiento",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name="compra",
            index=models.Index(
                fields=["comercio", "-fecha"], name="compras_com_comerci_330888_idx"
            ),
        ),
        migrations.AddField(
            model_name="comprapago",
            name="caja_sesion",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="caja.cajasesion",
            ),
        ),
        migrations.AddField(
            model_name="comprapago",
            name="comercio",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="core.comercio"
            ),
        ),
        migrations.AddField(
            model_name="comprapago",
            name="compra",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="pagos",
                to="compras.compra",
            ),
        ),
        migrations.AddField(
            model_name="comprapago",
            name="cuenta",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="caja.cuentapago",
            ),
        ),
        migrations.AddIndex(
            model_name="comprapago",
            index=models.Index(
                fields=["comercio", "fecha"], name="compras_com_comerci_0cbd1a_idx"
            ),
        ),
    ]
