# Generated by Django 6.1 on 2026-08-31 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0003_comprapago_compra_fecha_vencimiento_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compraitem',
            name='costo_unitario',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=14),
        ),
    ]
