# Generated by Django 6.1 on 2026-08-21 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="comercio",
            name="asistente_consultas_diarias",
            field=models.IntegerField(default=0),
        ),
    ]
