# Generated by Django 6.1 on 2026-08-21 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_comercio_asistente_consultas_diarias"),
    ]

    operations = [
        migrations.AddField(
            model_name="comercio",
            name="asistente_api_key_cifrada",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="comercio",
            name="asistente_modelo",
            field=models.CharField(blank=True, default="", max_length=60),
        ),
    ]
