# Generated by Django 6.1 on 2026-08-23 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_comercio_asistente_api_key_cifrada_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="comercio",
            name="permitir_venta_sin_stock",
            field=models.BooleanField(default=True),
        ),
    ]
