# Generated by Django 6.1 on 2026-08-29 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_comercio_permitir_venta_sin_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuariocomercio',
            name='modulos_bloqueados',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
