# Generated by Django 6.1 on 2026-08-31 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_usuariocomercio_modulos_bloqueados'),
    ]

    operations = [
        migrations.AddField(
            model_name='comercio',
            name='color_acento',
            field=models.CharField(blank=True, default='', max_length=7),
        ),
    ]
